const lessons=[{name:"A1: Przedstawianie się",items:[{de:"Ich heiße Anna.",pl:"Nazywam się Anna."},{de:"Wie heißt du?",pl:"Jak się nazywasz?"},{de:"Ich komme aus Polen.",pl:"Pochodzę z Polski."},{de:"Ich wohne in Heidelberg.",pl:"Mieszkam w Heidelbergu."}]},{name:"A1: Codzienne zdania",items:[{de:"Guten Morgen.",pl:"Dzień dobry rano."},{de:"Mir geht es gut.",pl:"Mam się dobrze."},{de:"Ich lerne Deutsch.",pl:"Uczę się niemieckiego."},{de:"Ich spreche ein bisschen Deutsch.",pl:"Mówię trochę po niemiecku."}]},{name:"A1/A2: Zakupy",items:[{de:"Ich möchte Brot kaufen.",pl:"Chciałabym kupić chleb."},{de:"Wie viel kostet das?",pl:"Ile to kosztuje?"},{de:"Ich brauche Milch und Eier.",pl:"Potrzebuję mleka i jajek."},{de:"Kann ich mit Karte bezahlen?",pl:"Czy mogę zapłacić kartą?"}]},{name:"Hotel / Hausdame",items:[{de:"Das Zimmer ist fertig.",pl:"Pokój jest gotowy."},{de:"Ich brauche frische Handtücher.",pl:"Potrzebuję świeżych ręczników."},{de:"Die Rezeption hat angerufen.",pl:"Recepcja zadzwoniła."},{de:"Im Badezimmer fehlt Seife.",pl:"W łazience brakuje mydła."},{de:"Der Gast braucht ein neues Kissen.",pl:"Gość potrzebuje nowej poduszki."}]}];
let currentLesson=0,currentItem=0,points=Number(localStorage.getItem("annaPremium_points")||0),badges=Number(localStorage.getItem("annaPremium_badges")||0);
const teacher=document.getElementById("teacher"),phrase=document.getElementById("phrase"),translation=document.getElementById("translation"),speechBubble=document.getElementById("speechBubble"),heardText=document.getElementById("heardText"),result=document.getElementById("result"),lessonSelect=document.getElementById("lessonSelect"),pointsEl=document.getElementById("points"),badgesEl=document.getElementById("badges"),levelEl=document.getElementById("level"),progressFill=document.getElementById("progressFill"),progressText=document.getElementById("progressText");
function normalize(t){return t.toLowerCase().replace(/[.,!?]/g,"").replace(/ä/g,"ae").replace(/ö/g,"oe").replace(/ü/g,"ue").replace(/ß/g,"ss").trim()}
function similarity(a,b){a=normalize(a);b=normalize(b);if(!a||!b)return 0;const aw=a.split(/\s+/),bw=b.split(/\s+/);let same=0;for(const w of bw)if(aw.includes(w))same++;return same/Math.max(aw.length,bw.length)}
function currentSentence(){return lessons[currentLesson].items[currentItem]}
function fillLessons(){lessons.forEach((l,i)=>{const o=document.createElement("option");o.value=i;o.textContent=l.name;lessonSelect.appendChild(o)})}
function showPhrase(){const item=currentSentence();phrase.textContent=item.de;translation.textContent=item.pl;speechBubble.textContent=item.de;heardText.textContent="—";result.textContent="Posłuchaj Anny i powtórz zdanie."}
function updateStats(){pointsEl.textContent=points;badgesEl.textContent=badges;let level="A1";if(points>=40)level="B1";else if(points>=20)level="A2";const p=Math.min(points/40*100,100);levelEl.textContent=level;progressText.textContent=`Poziom ${level} · ${Math.round(p)}% drogi do B1`;progressFill.style.width=p+"%";localStorage.setItem("annaPremium_points",points);localStorage.setItem("annaPremium_badges",badges)}
function happy(){teacher.classList.add("happy");setTimeout(()=>teacher.classList.remove("happy"),900)}
function speakGerman(text){if(!("speechSynthesis"in window)){result.textContent="Ta przeglądarka nie obsługuje głosu.";return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang="de-DE";u.rate=.82;u.pitch=1.05;const voices=speechSynthesis.getVoices();u.voice=
    voices.find(v=>v.lang.startsWith("de") && v.name.toLowerCase().includes("google")) ||
    voices.find(v=>v.lang.startsWith("de") && v.name.toLowerCase().includes("katja")) ||
    voices.find(v=>v.lang.startsWith("de") && v.name.toLowerCase().includes("anna")) ||
    voices.find(v=>v.lang.startsWith("de")) ||
    null;speechBubble.textContent=text;u.onstart=()=>teacher.classList.add("speaking");u.onend=()=>teacher.classList.remove("speaking");u.onerror=()=>teacher.classList.remove("speaking");speechSynthesis.speak(u)}
function listenAndCheck(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){result.textContent="❌ Ta przeglądarka nie obsługuje rozpoznawania mowy. Spróbuj w Chrome albo Edge.";return}const r=new SR();r.lang="de-DE";r.interimResults=false;r.maxAlternatives=1;result.textContent="🎤 Słucham... Proszę powiedzieć zdanie po niemiecku.";speechBubble.textContent="Ich höre zu...";r.start();r.onresult=e=>{const heard=e.results[0][0].transcript;heardText.textContent=heard;const score=similarity(heard,currentSentence().de);if(score>=.85){result.textContent="✅ Sehr gut! Bardzo dobrze. +2 punkty";speechBubble.textContent="Sehr gut! Das war richtig.";points+=2;happy()}else if(score>=.55){result.textContent="⚠️ Prawie dobrze. +1 punkt. Powtórz jeszcze raz.";speechBubble.textContent="Fast richtig. Versuch es noch einmal.";points+=1}else{result.textContent="❌ Spróbuj jeszcze raz. Kliknij „Powtórz głos”.";speechBubble.textContent="Bitte wiederhole den Satz."}if(points>0&&points%10===0){badges+=1;result.textContent+=" 🏆 Nowa odznaka!"}updateStats()};r.onerror=()=>{result.textContent="❌ Nie udało się rozpoznać głosu. Sprawdź mikrofon i zgodę w przeglądarce.";speechBubble.textContent="Bitte prüfe dein Mikrofon."}}
function nextPhrase(){currentItem++;if(currentItem>=lessons[currentLesson].items.length)currentItem=0;showPhrase();speakGerman(currentSentence().de)}
function askQuiz(){const qs=[{q:"Wie heißt du?",hint:"Odpowiedz: Ich heiße ..."},{q:"Wo wohnst du?",hint:"Odpowiedz: Ich wohne in ..."},{q:"Wie geht es dir?",hint:"Odpowiedz: Mir geht es gut."},{q:"Was brauchst du im Hotel?",hint:"Odpowiedz: Ich brauche ..."},{q:"Ist das Zimmer fertig?",hint:"Odpowiedz: Ja, das Zimmer ist fertig."}];const item=qs[Math.floor(Math.random()*qs.length)];document.getElementById("quizQuestion").textContent=item.q;document.getElementById("quizHint").textContent=item.hint;speakGerman(item.q)}
document.getElementById("startBtn").addEventListener("click",()=>{showPhrase();speakGerman(currentSentence().de)});
document.getElementById("speakBtn").addEventListener("click",()=>speakGerman(currentSentence().de));
document.getElementById("listenBtn").addEventListener("click",listenAndCheck);
document.getElementById("nextBtn").addEventListener("click",nextPhrase);
document.getElementById("quizBtn").addEventListener("click",askQuiz);
lessonSelect.addEventListener("change",e=>{currentLesson=Number(e.target.value);currentItem=0;showPhrase()});
speechSynthesis.onvoiceschanged=()=>{};fillLessons();updateStats();showPhrase();
